[package]
name = "dsmon-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Shared egui interface for DeepSeek Balance Monitor"

[dependencies]
dsmon-core = { path = "../dsmon-core" }
chrono.workspace = true
eframe.workspace = true
egui.workspace = true
egui_plot.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ksni = { workspace = true, features = ["blocking"] }

[target.'cfg(windows)'.dependencies]
tray-icon.workspace = true
